/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookCondition = IDL.Variant({
  'new' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
  'likeNew' : IDL.Null,
});
export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'sellerPhone' : IDL.Text,
  'sold' : IDL.Bool,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'author' : IDL.Text,
  'imageKey' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'priceInCents' : IDL.Nat,
  'condition' : BookCondition,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CreateBookInput = IDL.Record({
  'title' : IDL.Text,
  'sellerPhone' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'imageKey' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'priceInCents' : IDL.Nat,
  'condition' : BookCondition,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseBooks' : IDL.Func(
      [IDL.Text, IDL.Opt(BookCondition), IDL.Text],
      [IDL.Vec(Book)],
      ['query'],
    ),
  'deleteBook' : IDL.Func([IDL.Nat], [], []),
  'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBook' : IDL.Func([CreateBookInput], [IDL.Nat], []),
  'markAsSold' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookCondition = IDL.Variant({
    'new' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'likeNew' : IDL.Null,
  });
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'sellerPhone' : IDL.Text,
    'sold' : IDL.Bool,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'author' : IDL.Text,
    'imageKey' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'priceInCents' : IDL.Nat,
    'condition' : BookCondition,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CreateBookInput = IDL.Record({
    'title' : IDL.Text,
    'sellerPhone' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'imageKey' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'priceInCents' : IDL.Nat,
    'condition' : BookCondition,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseBooks' : IDL.Func(
        [IDL.Text, IDL.Opt(BookCondition), IDL.Text],
        [IDL.Vec(Book)],
        ['query'],
      ),
    'deleteBook' : IDL.Func([IDL.Nat], [], []),
    'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBook' : IDL.Func([CreateBookInput], [IDL.Nat], []),
    'markAsSold' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };